language: java
sudo: false

jdk:
  - oraclejdk8
  
env:
  - DISPLAY=:99.0

before_install:
  - "sh -e /etc/init.d/xvfb start"

install:
  - mvn install -DskipTests=true -Dgpg.skip=true -Dmaven.javadoc.skip=true -B -V 

script:
  - mvn package -Dgpg.skip=true

before_cache:
  - rm -fr $HOME/.m2/repository/net/mikehardy/google-analytics-java

cache:
  directories:
    - $HOME/.m2
